### ISSUE TITLE
Proper installation

### ISSUE THREAD

**Issue by bunopus** [dart-lang/angular_analyzer_plugin#432] opened 2017-09-11 21:40 UTC
Sorry, it's not a bug, but i spend couple of hours trying to figure out what's wrong with my setup with no luck. According to README
1. _dart --version_ `Dart VM version: 1.25.0-dev.16.3 (Mon Sep 11 04:02:59 2017) on "macos_x64"
`
2. Open WebStorm, create a new Project from Dart template (Angular application)
3. pubspec.yaml
```
name: test_plugin
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: eugene.gusev <email@example.com>

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_components: ^0.6.0

dev_dependencies:
  angular_test: ^1.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

transformers:
- angular:
    entry_points:
      - web/main.dart
      - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
web:
  compiler:
    debug: dartdevc

```
Looks very close to one in _playground_ folder
4. analysis_options.yaml
```
analyzer:
  strong-mode: true
  plugins:
    angular:
      enabled: true
#   exclude:
#     - path/to/excluded/files/**

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
    - cancel_subscriptions
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps

# backwards compatible (you also need this, for the moment)
plugins:
  angular:
    enabled: true
```
5. Restart Analysis server (by pressing refresh icon)
6. Mess with templates - no errors

Am i miss something?

**Comment by MichaelRFairhurst** [comment] 2017-09-11 21:56
Thanks for filing!

I think this *is* a bug. I tried and it worked for me.

What version of WebStorm are you using?

**Comment by bunopus** [comment] 2017-09-12 08:08
@MichaelRFairhurst

**Comment by bunopus** [comment] 2017-09-12 08:10
@MichaelRFairhurst 
```
WebStorm 2017.1.4
Build #WS-171.4694.29, built on June 7, 2017

JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6
```
Maybe there are some prerequisites that i miss?

**Comment by MichaelRFairhurst** [comment] 2017-09-12 17:24
This version should be fine...I didn't list the requirement of 2016.3 but you are past that so that's not the issue.

Could you try perhaps clearing out `~/.dartServer/.analysis-driver/*` and then restart the analysis server?

If you have the time and are willing to collect more data so we can help more, you can hit Ctrl+Alt+Shift+/ (on mac...Command+Alt+Shift+/), to open the registry. You can look for the key `dart.server.additional.arguments` and add in the value `--instrumentation-log-file=/tmp/analysis_log`. After restarting the analysis server, it should start filling in `/tmp/analysis_log` with debug data (may includes sections of your project code as well). You can email the log to me at m fairhurst at google dot com, and maybe it will be clearer what the issue is.

**Comment by bunopus** [comment] 2017-09-13 13:10
i removed all content from `~/.dartServer/.analysis-driver/*` but no luck.
I sent you the logs.

**Comment by daniel-v** [comment] 2017-09-13 17:28
Followed the instructions above. I also have the same issue.

`Dart VM version: 1.25.0-dev.16.4 (Wed Sep 13 01:56:56 2017) on "windows_x64"`

For my project, .packages contains.

```
  analyzer:
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.30.0+2"
  angular:
    description:
      name: angular
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.0"
```

In the instrumentation log, I see some errors:

```
{
  "id": "3",
  "error": {
    "code": "SERVER_ERROR",
    "message": "NoSuchMethodError: The getter 'fullName' was called on null.\nReceiver: null\nTried calling: fullName",
    "stackTrace": "#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)\n#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:46)\n#2      PluginWatcher.addedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:63)\n#3      AnalysisDriverScheduler.add (package:analyzer/src/dart/analysis/driver.dart:1568)\n#4      new AnalysisDriver (package:analyzer/src/dart/analysis/driver.dart:325)\n#5      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:169)\n#6      ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:1133)\n#7      ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1095)\n#8      ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1133)\n#9      ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:761)\n#10     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:865)\n#11     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:329)\n#12     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:254)\n#13     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:694)\n#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)\n#15     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:690)\n#16     _rootRun (dart:async/zone.dart:1120)\n#17     _CustomZone.run (dart:async/zone.dart:1001)\n#18     _CustomZone.runGuarded (dart:async/zone.dart:901)\n#19     runZoned (dart:async/zone.dart:1465)\n#20     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:689)\n#21     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:172)\n#22     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)\n#23     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163)\n#24     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)\n#25     _rootRunUnary (dart:async/zone.dart:1128)\n#26     _CustomZone.runUnary (dart:async/zone.dart:1012)\n#27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)\n#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)\n#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)\n#30     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)\n#31     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)\n#32     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)\n#33     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:156)\n#34     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131)\n#35     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)\n#36     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)\n#37     _rootRunUnary (dart:async/zone.dart:1128)\n#38     _CustomZone.runUnary (dart:async/zone.dart:1012)\n#39     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)\n#40     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)\n#41     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)\n#42     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)\n#43     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)\n#44     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)\n#45     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)\n#46     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)\n#47     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)\n#48     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)\n#49     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)\n#50     _rootRunUnary (dart:async/zone.dart:1128)\n#51     _CustomZone.runUnary (dart:async/zone.dart:1012)\n#52     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)\n#53     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)\n#54     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)\n#55     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)\n#56     _StreamController._add (dart:async/stream_controller.dart:667)\n#57     _StreamController.add (dart:async/stream_controller.dart:613)\n#58     _Socket._onData (dart:io-patch/socket_patch.dart:1643)\n#59     _rootRunUnary (dart:async/zone.dart:1132)\n#60     _CustomZone.runUnary (dart:async/zone.dart:1012)\n#61     _CustomZone.runUnaryGuarded (dart:async/zone.dart:909)\n#62     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)\n#63     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)\n#64     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)\n#65     _StreamController._add (dart:async/stream_controller.dart:667)\n#66     _StreamController.add (dart:async/stream_controller.dart:613)\n#67     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1228)\n#68     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)\n#69     _microtaskLoop (dart:async/schedule_microtask.dart:41)\n#70     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)\n#71     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)\n#72     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)\n"
  }
}
```

**Comment by daniel-v** [comment] 2017-09-13 17:56
Not sure if I am on the right track but it seems that the error is because the plugin's package can't be resolved - never downloaded `angular_analyzer_plugin` before. I kind of expected that it would just automagically appear on my drive :)

I suspect, source is null here: `https://github.com/dart-lang/sdk/blob/4aeedec64e8522eff641d5c98f96ae89d4aa7f8e/pkg/analysis_server/lib/src/plugin/plugin_watcher.dart#L60`

I could make the in the instrumentation log go away by adding the following to my tiny project's pubspec:


```yaml
name: some_unique_name_sdfjhkseufh
description: QuickStart
version: 0.0.1

dependencies:
  angular: ^4.0.0

dev_dependencies:
  angular_analyzer_plugin:

dependency_overrides:
  dart_style: 1.0.7
  angular_compiler: 0.3.0
  analyzer: 0.31.0-alpha.1
```

Analyzer now runs but still am not getting any warnings/errors. It's as if the plugin was not working.

**Comment by MichaelRFairhurst** [comment] 2017-09-13 18:08
@daniel-v what is your `analysis_options.yaml`?

I think you're on the right track, but I think the issue is either that you've specified `angular_analyzer_plugin` instead of `angular`:

```
analyzer:
  plugins:
    angular_analyzer_plugin: # this should be `angular`
     enabled: true
```

or that you haven't yet run `pub get`.

The analysis server should, behind the scenes, download angular, find a special `tools/analyzer_plugin` directory, which has a `pubspec.yaml` file that imports `angular_analyzer_plugin`, and then it should run `pub get`. So you shouldn't need to specify `angular_analyzer_plugin` yourself anywhere.

**Comment by daniel-v** [comment] 2017-09-13 18:15
Indeed, I had angular_analyzer_plugin instead of angular in analysis_options.yaml. I've updated as per your comment. Currently it looks like:

```yaml
analyzer:
  plugins:
    angular:
      enabled: true

plugins:
  angular:
    enabled: true
```

Instrumentation log shows no error like it used to. Ran a `pub upgrade` (just to be on the safe side). Restarted analysis server and still no errors/hints/warnings.

**Comment by MichaelRFairhurst** [comment] 2017-09-13 20:33
CC @bwilkerson  this seems like maybe an SDK bug.

The analysis log that I got from @bunopus doesn't include any calls to load the analzyer plugin. @bunopus do you have any issue with me forwarding the logs to Brian?

@daniel-v would you also be able to send or attach your analysis logs as well?

**Comment by daniel-v** [comment] 2017-09-13 20:35
Sure, will do.

How does a line in the log file look like that indicates the loading of the plugin? (would be nice to know what I'm looking for :) )

**Comment by MichaelRFairhurst** [comment] 2017-09-13 21:01
This is what I see in my logs:

```
1505271808738:PluginReq:{"id"::"0","method"::"plugin.versionCheck","params"::{"byteStorePath"::"/home/mfairhurst/.dartServer/.analysis-driver","sdkPath"::"/home/mfairhurst/.dart-sdk","version"::"1.0.0-alpha.0"}}:file::///home/mfairhurst/.dartServer/.plugin_manager/e427d9fbf092a60fd5796fb62b99db85/analyzer_plugin/bin/plugin.dart::
1505271808772:PluginRes:{"id"::"0","requestTime"::1505271808751,"result"::{"isCompatible"::true,"name"::"Angular Analysis Plugin","version"::"1.0.0-alpha.0","contactInfo"::"Please file issues at https:://github.com/dart-lang/angular_analyzer_plugin","interestingFiles"::["*.dart","*.html"]}}:file::///home/mfairhurst/.dartServer/.plugin_manager/e427d9fbf092a60fd5796fb62b99db85/analyzer_plugin/bin/plugin.dart::
1505271808777:PluginReq:{"id"::"1","method"::"analysis.setContextRoots","params"::{"roots"::[{"root"::"/home/mfairhurst/dart/issue-432","exclude"::["/home/mfairhurst/dart/issue-432/.idea","/home/mfairhurst/dart/issue-432/.pub","/home/mfairhurst/dart/issue-432/build"],"optionsFile"::"/home/mfairhurst/dart/issue-432/analysis_options.yaml"}]}}:file::///home/mfairhurst/.dartServer/.plugin_manager/e427d9fbf092a60fd5796fb62b99db85/analyzer_plugin/bin/plugin.dart::
1505271808778:PluginReq:{"id"::"2","method"::"analysis.setSubscriptions","params"::{"subscriptions"::{"NAVIGATION"::["/home/mfairhurst/dart/issue-432/lib/test.dart"],"HIGHLIGHTS"::["/home/mfairhurst/dart/issue-432/lib/test.dart"]}}}:file::///home/mfairhurst/.dartServer/.plugin_manager/e427d9fbf092a60fd5796fb62b99db85/analyzer_plugin/bin/plugin.dart::
1505271808778:PluginReq:{"id"::"3","method"::"analysis.setPriorityFiles","params"::{"files"::["/home/mfairhurst/dart/issue-432/lib/test.dart"]}}:file::///home/mfairhurst/.dartServer/.plugin_manager/e427d9fbf092a60fd5796fb62b99db85/analyzer_plugin/bin/plugin.dart::
1505271809050:PluginRes:{"id"::"1","requestTime"::1505271808777}:file::///home/mfairhurst/.dartServer/.plugin_manager/e427d9fbf092a60fd5796fb62b99db85/analyzer_plugin/bin/plugin.dart::
1505271809067:PluginRes:{"id"::"2","requestTime"::1505271809063}:file::///home/mfairhurst/.dartServer/.plugin_manager/e427d9fbf092a60fd5796fb62b99db85/analyzer_plugin/bin/plugin.dart::
1505271809078:PluginRes:{"id"::"3","requestTime"::1505271809067}:file::///home/mfairhurst/.dartServer/.plugin_manager/e427d9fbf092a60fd5796fb62b99db85/analyzer_plugin/bin/plugin.dart::
1505271813959:PluginNoti:{"event"::"analysis.errors","params"::{"file"::"/home/mfairhurst/dart/issue-432/lib/test.dart","errors"::[]}}:file::///home/mfairhurst/.dartServer/.plugin_manager/e427d9fbf092a60fd5796fb62b99db85/analyzer_plugin/bin/plugin.dart::
1505271813962:Noti:{"event"::"analysis.errors","params"::{"file"::"/home/mfairhurst/dart/issue-432/lib/test.dart","errors"::[]}}
1505271813966:PluginNoti:{"event"::"analysis.navigation","params"::{"file"::"/home/mfairhurst/dart/issue-432/lib/test.dart","regions"::[],"targets"::[],"files"::[]}}:file::///home/mfairhurst/.dartServer/.plugin_manager/e427d9fbf092a60fd5796fb62b99db85/analyzer_plugin/bin/plugin.dart::
```

**Comment by bunopus** [comment] 2017-09-13 21:52
@MichaelRFairhurst 
>do you have any issue with me forwarding the logs to Brian?

no problem

**Comment by daniel-v** [comment] 2017-09-14 09:42
I checked, I have a `.dartServer/.plugin_manager` folder with the analyzer plugin in it.

**Comment by bwilkerson** [comment] 2017-09-14 20:11
The exception thrown when a package listed under `plugins` isn't resolvable has been fixed (https://dart-review.googlesource.com/c/sdk/+/5885).

**Comment by bunopus** [comment] 2017-09-14 20:51
Any chance that it will help with the original issue? Because actually i don`t have this error in logs

**Comment by bwilkerson** [comment] 2017-09-14 20:53
Sorry, but no. I was just recording that a secondary issue that was reported in this thread was fixed. I don't yet understand the cause of the original issue.

**Comment by daniel-v** [comment] 2017-09-19 09:20
Anything more I can do on my end to help here?

**Comment by MichaelRFairhurst** [comment] 2017-09-20 16:24
Sorry @bunopus and @daniel-v. We are still scratching our heads without more information...

I suppose, if either of you would be willing to zip up your entire project in which its not working, that might answer some questions for us?

Otherwise, we're going to have to add more logging, and we're low on cycles for that right now. But we *will* get to it.

**Comment by zoechi** [comment] 2017-09-20 18:49
It seems it stopped working for me after a Dart update recently (to a newer 1.25.0-dev.xx version) on a project where it already worked with the new configuration in analysis_options, but I'm currently not working on an Angular project and didn't have time yet to investigate further.

**Comment by bunopus** [comment] 2017-09-20 21:11
Thanks @MichaelRFairhurst! I can zip my project, but it`s just a template from WebStorm, so i don`t think it will help. Maybe it works for others because you have installed this plugin before? Anyway, i will try to test it on the clean machine.

**Comment by daniel-v** [comment] 2017-09-21 00:01
Same here. It is just a template from Webstorm.

I managed to track down the problem to first run. `Process.runSync()` in this line never returned: https://github.com/dart-lang/sdk/blob/4aeedec64e8522eff641d5c98f96ae89d4aa7f8e/pkg/analysis_server/lib/src/plugin/plugin_manager.dart#L616

Next time when the server was started `_computePaths` was invoked with `runPub: false` parameter and thus `pub get` never ran successfully for the analyzer plugin.

I manually ran it from command prompt and let there be light! I started seeing analyzer plugin in instrumentation logs:

```
1505951651391:PluginEx:NoSuchMethodError:: The getter 'typeParameters' was called on null.
Receiver:: null
Tried calling:: typeParameters:#0      Object._noSuchMethod (dart::core-patch/object_patch.dart::42)
#1      Object.noSuchMethod (dart::core-patch/object_patch.dart::46)
#2      BindingTypeSynthesizer._instantiateClass (package::angular_analyzer_plugin/src/directive_extraction.dart::629::33)
#3      new BindingTypeSynthesizer (package::angular_analyzer_plugin/src/directive_extraction.dart::570::34)
#4      DirectiveLinker.resynthesizeDirectives (package::angular_analyzer_plugin/src/directive_linking.dart::60::38)
<asynchronous suspension>
#5      AngularDriver.resynthesizeDirectives (package::angular_analyzer_plugin/src/angular_driver.dart::738::33)
<asynchronous suspension>
#6      AngularDriver.getAngularAnnotatedClasses (package::angular_analyzer_plugin/src/angular_driver.dart::772::15)
<asynchronous suspension>
#7      AngularDriver.getUnlinkedClasses (package::angular_analyzer_plugin/src/angular_driver.dart::758::14)
<asynchronous suspension>
#8      ChildDirectiveLinker.matchDirective (package::angular_analyzer_plugin/src/directive_linking.dart::513::38)
<asynchronous suspension>
#9      ChildDirectiveLinker._addDirectivesAndElementTagsForDartObject (package::angular_analyzer_plugin/src/directive_linking.dart::546::33)
<asynchronous suspension>
#10     ChildDirectiveLinker.lookupDirectiveFromLibrary (package::angular_analyzer_plugin/src/directive_linking.dart::445::17)
<asynchronous suspension>
#11     ChildDirectiveLinker.linkDirectivesAndPipes (package::angular_analyzer_plugin/src/directive_linking.dart::370::19)
<asynchronous suspension>
#12     AngularDriver.resolveDart (package::angular_analyzer_plugin/src/angular_driver.dart::642::18)
<asynchronous suspension>
#13     AngularDriver.pushDartErrors (package::angular_analyzer_plugin/src/angular_driver.dart::574::26)
<asynchronous suspension>
#14     AngularDriver.performWork (package::angular_analyzer_plugin/src/angular_driver.dart::253::7)
<asynchronous suspension>
#15     AnalysisDriverScheduler._run (package::analyzer/src/dart/analysis/driver.dart::1651::24)
<asynchronous suspension>
#16     AnalysisDriverScheduler.start (package::analyzer/src/dart/analysis/driver.dart::1594::5)
#17     new ServerPlugin (package::analyzer_plugin/plugin/plugin.dart::100::29)
#18     new ServerPlugin&CompletionMixin (package::analyzer_plugin/plugin/completion_mixin.dart::23::1)
#19     new ServerPlugin&CompletionMixin&NavigationMixin (package::analyzer_plugin/plugin/navigation_mixin.dart::50::1)
#20     new AngularAnalyzerPlugin (package::angular_analyzer_plugin/plugin.dart::34::54)
#21     start (package::angular_analyzer_plugin/starter.dart::13::15)
#22     main (file::///C::/Users/Dani/AppData/Local/.dartServer/.plugin_manager/4af399bd2d8408a770b6aaa76986efde/analyzer_plugin/bin/plugin.dart::6::3)
#23     _startIsolate.<anonymous closure> (dart::isolate-patch/isolate_patch.dart::261)
#24     _RawReceivePortImpl._handleMessage (dart::isolate-patch/isolate_patch.dart::151)
```

`Dart VM version: 1.25.0-dev.16.4 (Wed Sep 13 01:56:56 2017) on "windows_x64"`

**Comment by MichaelRFairhurst** [comment] 2017-09-21 00:14
Awesome work @daniel-v !!

Yes. That exception should be separate issue :( Can you try clearing out `~/.dartServer/.analysis-driver/*.ng*` and see if that fixes this last issue for you? Or it may be related to if your file is in a weird state like `@Component() class {}` or something else, some half-written state I haven't been able to pin down yet.

**Comment by MichaelRFairhurst** [comment] 2017-09-21 00:16
@bunopus you should be able to try the same fix by 

```
cd ~/.dartServer/.plugin-manager/??????????
cd analyzer_plugin
pub get
```

and then restarting your analysis server.

I'm not sure what the `??????????` section will be for you, though. You may want to run it for all directories you see within `~/.dartServer/.plugin-manager`.

**Comment by daniel-v** [comment] 2017-09-21 00:21
@MichaelRFairhurst clearing the `.analysis-driver` folder and restarting the server did not resolve the exception.

I hope @bunopus will be able to get it working. If so, it could be that my environment is messed up. If not, that's gonna be another 2.5 hours of debugging.

**Comment by MichaelRFairhurst** [comment] 2017-09-21 00:30
@daniel-v very interesting. The error makes it look like you have annotated a class *which does not exist* as a `@Directive` or `@Component`. I thought it could only occur under some crazy race conditions.

I'll make a new ticket for that, though, we'll see if it ends up being the same issue really.

**Comment by lexaknyazev** [comment] 2017-09-22 13:31
Not sure if it's the same bug, but I see analyzer crashing on adding angular plugin.
Repro steps:

1. Delete `.dartServer` folder.
2. Open IDEA, create ToDo AngularDart sample. `pubspec.yaml` looks like this:
```yaml
name: todo
description: A web app that uses AngularDart Components
version: 0.0.1

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  angular: ^4.0.0
  angular_components: ^0.6.0

dev_dependencies:
  angular_test: ^1.0.0
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  test: ^0.12.0

transformers:
- angular:
    entry_points:
      - web/main.dart
      - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
```
3. Add to `analysis_options.yaml` (in both places)
```yaml
plugins:
  angular:
    enabled: true
```
4. Click "Restart Dart Analysis Server" button.
5. Analyzer crashes:
```
IDEA IU-172.4155.36 

Dart analysis server, SDK version 2.0.0-dev.1.0, server version 1.18.4, FATAL error: Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\todo], excluded: [C:\todo\.idea, C:\todo\.pub, C:\todo\build, C:\todo\out]}, clientRequestTime: 1506084969777}
ProcessException: The system cannot find the file specified.

  Command: C:\dart\dev\bin\pub get
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:473)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:622)
#2      Process.runSync (dart:io-patch/process_patch.dart:64)
#3      PluginManager._computePaths (package:analysis_server/src/plugin/plugin_manager.dart:616)
#4      PluginManager.pathsFor (package:analysis_server/src/plugin/plugin_manager.dart:462)
#5      PluginManager.addPluginToContextRoot (package:analysis_server/src/plugin/plugin_manager.dart:342)
<asynchronous suspension>
#6      PluginWatcher.addedDriver (package:analysis_server/src/plugin/plugin_watcher.dart:73)
#7      AnalysisDriverScheduler.add (package:analyzer/src/dart/analysis/driver.dart:1602)
#8      new AnalysisDriver (package:analyzer/src/dart/analysis/driver.dart:332)
#9      ContextBuilder.buildDriver (package:analyzer/src/context/builder.dart:169)
#10     ServerContextManagerCallbacks.addAnalysisDriver (package:analysis_server/src/analysis_server.dart:1132)
#11     ContextManagerImpl._createContext (package:analysis_server/src/context_manager.dart:1101)
#12     ContextManagerImpl._createContexts (package:analysis_server/src/context_manager.dart:1139)
#13     ContextManagerImpl.setRoots (package:analysis_server/src/context_manager.dart:761)
#14     AnalysisServer.setAnalysisRoots (package:analysis_server/src/analysis_server.dart:864)
#15     AnalysisDomainHandler.setAnalysisRoots (package:analysis_server/src/domain_analysis.dart:329)
#16     AnalysisDomainHandler.handleRequest (package:analysis_server/src/domain_analysis.dart:254)
#17     AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:693)
#18     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#19     AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:689)
#20     _rootRun (dart:async/zone.dart:1124)
#21     _CustomZone.run (dart:async/zone.dart:1021)
#22     runZoned (dart:async/zone.dart:1488)
#23     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:688)
#24     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:172)
#25     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:200)
#26     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:163)
#27     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:108)
#28     _rootRunUnary (dart:async/zone.dart:1132)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029)
#30     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#33     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#34     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#35     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#36     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:156)
#37     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:131)
#38     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:189)
#39     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#40     _rootRunUnary (dart:async/zone.dart:1132)
#41     _CustomZone.runUnary (dart:async/zone.dart:1029)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#45     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:68)
#46     _EventSinkWrapper.add (dart:async/stream_transformers.dart:15)
#47     _StringAdapterSink.add (dart:convert/string_conversion.dart:268)
#48     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:273)
#49     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:348)
#50     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:341)
#51     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:86)
#52     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:120)
#53     _rootRunUnary (dart:async/zone.dart:1132)
#54     _CustomZone.runUnary (dart:async/zone.dart:1029)
#55     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
#56     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#57     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#58     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#59     _StreamController._add (dart:async/stream_controller.dart:667)
#60     _StreamController.add (dart:async/stream_controller.dart:613)
#61     _Socket._onData (dart:io-patch/socket_patch.dart:1643)
#62     _rootRunUnary (dart:async/zone.dart:1136)
#63     _CustomZone.runUnary (dart:async/zone.dart:1029)
#64     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931)
#65     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#66     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#67     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#68     _StreamController._add (dart:async/stream_controller.dart:667)
#69     _StreamController.add (dart:async/stream_controller.dart:613)
#70     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1228)
#71     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:784)
#72     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#73     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#74     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:99)
#75     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:152)
```

```
1506084969715 started analysis server:
  C:\dart\dev\bin\dart.exe C:\dart\dev\bin\snapshots\analysis_server.dart.snapshot --client-id=IntelliJ-IDEA --client-version=IU-172.4155.36 --useAnalysisHighlight2
1506084970231 <= {"event":"server.connected","params":{"version":"1.18.4","pid":18048,"sessionId":""}}
1506084970250 <= {"id":"0","result":{"version":"1.18.4"}}
1506084970251 => {"id":"1","method":"server.setSubscriptions","params":{"subscriptions":["STATUS"]},"clientRequestTime":1506084969771}
1506084970252 => {"id":"2","method":"analysis.updateOptions","params":{"options":{"enableAsync":true,"enableDeferredLoading":true,"enableEnums":true,"enableNullAwareOperators":true,"enableSuperMixins"
1506084970252 => {"id":"3","method":"analysis.setAnalysisRoots","params":{"included":["C:\\todo"],"excluded":["C:\\todo\\.idea","C:\\todo\\.pub","C:\\todo\\build","C:\\todo\\out"]},"clientRequestTime"
1506084970252 => {"id":"4","method":"analysis.setPriorityFiles","params":{"files":["C:\\todo\\web\\main.dart"]},"clientRequestTime":1506084969780}
1506084970252 => {"id":"5","method":"analysis.setSubscriptions","params":{"subscriptions":{"HIGHLIGHTS":["C:\\todo\\web\\main.dart"],"OVERRIDES":["C:\\todo\\web\\main.dart"],"NAVIGATION":["C:\\todo\\w
1506084970252 => {"id":"6","method":"edit.getAssists","params":{"file":"C:\\todo\\web\\main.dart","offset":0,"length":0},"clientRequestTime":1506084969794}
1506084970255 <= {"id":"1"}
1506084970259 <= {"id":"2"}
1506084970276 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":true}}}
1506084970284 <= {"event":"server.status","params":{"pub":{"isListingPackageDirs":false}}}
1506084971728 <= {"event":"analysis.errors","params":{"file":"C:\\todo\\analysis_options.yaml","errors":[]}}
1506084971836 <= {"id":"3"}
1506084971838 <= {"id":"4"}
1506084971844 <= {"id":"5"}
1506084971881 <= {"event":"server.error","params":{"isFatal":true,"message":"Failed to handle request: {id: 3, method: analysis.setAnalysisRoots, params: {included: [C:\\todo], excluded: [C:\\todo\\.i
```
6. Analyzer doesn't crash on subsequent re-runs, but Angular remains unrecognized.

**Comment by MichaelRFairhurst** [comment] 2018-03-26 20:26
Closing this after doing extensive windows testing etc. The latest version should now be much more stable on windows, and there is a troubleshooting section with a lot more detail.

Sincere apologies and thanks to all who ran into issues and helped collect information on what was going wrong! Please do continue to send feedback for any issues!

**Closed by MichaelRFairhurst** 2018-03-26 20:26 UTC
Labels: P1 high, S1 high, Type: bug
