### ISSUE TITLE
Line break symbols are not counted correctly

### ISSUE THREAD

**Issue by alexander-doroshko** [dart-lang/angular_analyzer_plugin#130] opened 2016-12-05 12:13 UTC
I suppose that it is hardcoded somewhere inside the angular_analyzer_plugin that line break is presented with one symbol. It is not always the case, especially on Windows. In the worst case line breaks may be mixed.
#### Details about the use case with IntelliJ IDEA. 
When a file is saved on disk, Dart Analysis Server handles its contents as is, i.e. with CR+LF line endings. When a file is edited and not saved, IDE sends OverlaidContent to the DAS, and this overlaid content always has single-char LF line endings (because internally IDE operates line breaks  normalized to LF). So, offset of the same error must be completely different in 2 cases: file is saved and file is not saved. But line and column of the error must remain the same (provided that we type insignificant spaces at the end of file). When debugging errors reported by the angular_analyzer_plugin, I see that it doesn't update offset correctly, but incorrectly updates column instead. Here are two reports about the same error from DAS, one for saved file and one for unsaved:
```
[file=C:\dart_projects\angular-examples\toh-6\lib\hero_search_component.html, offset=158, length=7, startLine=5, startColumn=27]
[file=C:\dart_projects\angular-examples\toh-6\lib\hero_search_component.html, offset=158, length=7, startLine=5, startColumn=23]
```
Expected data (for saved and unsaved file):
```
[file=C:\dart_projects\angular-examples\toh-6\lib\hero_search_component.html, offset=158, length=7, startLine=5, startColumn=27]
[file=C:\dart_projects\angular-examples\toh-6\lib\hero_search_component.html, offset=154, length=7, startLine=5, startColumn=27]
```

**Comment by MichaelRFairhurst** [comment] 2016-12-05 17:40
Interesting! Great catch!

This is probably the reason for all of the terribly offset html squiggles in issue #122?

Hmm, I'm not following how this could cause the offset to be underreported and the column to be reported correctly...

This is what I would expect to happen based on my understanding of your description:

```
<html><CR-LF>
  <bad-tag><LF>
```

Here, the error for "bad-tag" before its saved should be at offset 11 (`<html>` + 2 + 2 spaces + `<`), and column 4, but its showing up at offset 10 (`<html>` + 1 + 2 spaces + '<'), and column 3 (since that's the actual column value of offset 10) before its saved. And after its saved its showing up correctly?

That's what I would expect to happen from the error but its not, unless I'm reading the expected/actual wrong.


Either way, I have a feeling that the problem is the html parser that we are using. Line endings strike again!

**Comment by MichaelRFairhurst** [comment] 2017-04-24 17:53
Removing help wanted, because this will either be fixed by, or have to be fixed in, angular_ast now.

**Comment by MichaelRFairhurst** [comment] 2017-04-24 17:58
@mk13 can you confirm if this is or isn't a problem with angular_ast?

**Comment by MichaelRFairhurst** [comment] 2017-05-17 17:34
ping @mk13  can you confirm if this is solved?

**Comment by mk13** [comment] 2017-05-17 22:15
Looks to be resolved after I switched to CRLF line-separator mode on intelliJ.

**Comment by MichaelRFairhurst** [comment] 2017-05-17 22:18
Great!

**Closed by MichaelRFairhurst** 2017-05-17 22:18 UTC
Labels: P2 medium, S1 high, Type: bug
