### ISSUE TITLE
Attribute Not allowed here

### ISSUE THREAD

**Issue by manuscle** [dart-lang/angular_analyzer_plugin#604] opened 2018-08-09 17:43 UTC
Hi,

In HTML templates, I don't have Dart/Angular support :
![selection_041](https://user-images.githubusercontent.com/596562/43915916-6dcc9930-9c0c-11e8-8c88-8d798aafe1e3.png)
How I can resolve this issue?

**Comment by MichaelRFairhurst** [comment] 2018-08-09 17:51
This is an intelliJ hint and we're looking at suppressing these automatically when the plugin is enabled.

You can disable it in your project by doing the following: settings -> editor -> inspections -> find HTML, uncheck all "unknown" html inspections.

Do you want to give that a try and see if that is indeed the issue?

**Comment by manuscle** [comment] 2018-08-10 06:31
Obviously, disabling inspection makes messages disappear.
But autocompletion does not work either.

**Comment by MichaelRFairhurst** [comment] 2018-08-10 17:43
Thanks!

I've done a less than stellar job tracking the Dart 2 migration, unfortunately. I think the reason why autocomplete isn't working is the same as #602, which I think is fixed by #605.

I see now your comment "I don't have Dart/Angular support." I had originally missed that, and thought it was only the issue with "attribute not allowed here."

I'll be doing a lot of testing with it even after I publish the fix to #602 because I am a bit concerned with what else might be lurking.

Thanks for reporting!

**Comment by MichaelRFairhurst** [comment] 2018-08-11 19:44
I believe the fix is published. If you want to give it a try with the fix (there are potentially still other issues that I will discover next week as I test more, though) then the next dev version of the SDK will auto-update you, in the meantime you can clear `~/.dartServer/.plugin-manager`.

**Comment by MichaelRFairhurst** [comment] 2018-08-12 21:40
I don't think all the kinks are worked out yet. If you are considering testing, I recommend waiting a bit!

I'm also going to mark this a duplicate of #602 because I think you're both experiencing the same issue. I'll report back when I'm confident its all solved!

**Closed by MichaelRFairhurst** 2018-08-12 21:40 UTC
