### ISSUE TITLE
ERROR: Expected an identifier. ([fhir_client] lib/webui/binary/code_value_component.dart:1)

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#177] opened 2016-12-20 18:47 UTC
I get this error on line1 one even when I add a few newlines at the beginning of the file.
Therefore I get no pointer where this error comes from.
Sorry, no idea how to make a reproduction.
The plugin showed an error for a missing `NgFor` and since I added that to `directives` (at least I haven't seen it previously) I get this error and haven't yet found a way to get rid of it.

Just found out that the error goes away when I remove the content of the 

    template: ``` .... ```

Ok, found it. `[data]=""` in
```html
<mdl-dropdown [(ngModel)]="value" (ngModelChange)="update()" [disabled]="readonly">
  <ul>
    <li menuItem [data]="" ></li>
    <li menuItem *ngFor="let item of valueSet?.codeSystem?.concept" [data]="item.code">{{item.display}}</li>
  </ul>
</mdl-dropdown>
```

Should provide better information about the error location.

**Comment by MichaelRFairhurst** [comment] 2016-12-20 20:38
Duplicate of #108

Yes, its currently a pretty awful experience to track it down!



Thank you for reporting all these issue Gunter!! Huge help as always!

**Closed** 2016-12-20 20:38 UTC
Labels: Resolution: duplicate
