### ISSUE TITLE
`src` property not recognized on `<img>`

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular_analyzer_plugin#257] opened 2017-03-28 08:23 UTC
```html
<img [src]="imageUrl">
```
> WARNING: The bound input src does not exist on any directives or on the element ([myproj] lib/webui/oauth2/google_login_button_component.html:1)

**Comment by zoechi** [comment] 2017-03-29 09:15
I forgot to mention that it also complains about the `alt` property.

**Comment by MichaelRFairhurst** [comment] 2017-03-31 19:03
Duplicate of #256

**Closed by MichaelRFairhurst** 2017-03-31 19:03 UTC
Labels: Resolution: duplicate
